# Generated by Django 3.0 on 2024-10-15 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=100)),
                ('rental_amount', models.CharField(max_length=100)),
                ('proof', models.CharField(max_length=100)),
                ('phoneno', models.IntegerField()),
                ('place', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=100)),
                ('pincode', models.BigIntegerField()),
                ('district', models.CharField(max_length=100)),
                ('property_type', models.CharField(max_length=100)),
                ('rental_period', models.CharField(max_length=100)),
                ('area_sqft', models.CharField(max_length=100)),
                ('rooms', models.CharField(max_length=100)),
                ('bathrooms', models.CharField(max_length=100)),
                ('furnishing', models.CharField(max_length=100)),
                ('parking', models.CharField(max_length=100)),
                ('kitchen', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=100)),
                ('latitude', models.CharField(default='', max_length=100)),
                ('longitude', models.CharField(default='', max_length=100)),
                ('reqstatus', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phoneno', models.BigIntegerField()),
                ('gender', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('place', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=100)),
                ('pincode', models.BigIntegerField()),
                ('district', models.CharField(max_length=100)),
                ('idproof', models.CharField(max_length=100)),
                ('Aadhar', models.CharField(max_length=100)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Login')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('rating', models.CharField(max_length=100)),
                ('review', models.CharField(max_length=100)),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.User')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('rental_period', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('HOME', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Home')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.User')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('REQUEST', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Request')),
            ],
        ),
        migrations.CreateModel(
            name='HouseOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phoneno', models.BigIntegerField()),
                ('gender', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('place', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=100)),
                ('pincode', models.BigIntegerField()),
                ('district', models.CharField(max_length=100)),
                ('idproof', models.CharField(max_length=100)),
                ('Aadhar', models.CharField(max_length=100)),
                ('status', models.CharField(default='', max_length=100)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Login')),
            ],
        ),
        migrations.AddField(
            model_name='home',
            name='OWNER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.HouseOwner'),
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('reply', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Login')),
            ],
        ),
    ]
